@startuml
!theme plain

actor Utilisateur as user
boundary Interface as interface
entity "Service " as filmService
entity "API" as API
entity "DAO" as dao
database "BDD" as db



user -> interface : **Clique** sur "ajouter à la watchlist"

interface->filmService: ajouter_a_watchlist(id_film)
filmService -> dao : **Recherche** dans la BDD
dao->db: recherche_watchlist_DAO(id_watchlist)
db->dao: Résultats 
dao->filmService: **Renvoi** de la liste de watchlist
filmService->interface: **Affichage** des watchlist disponibles


user -> interface : **Sélectionner** la watchlist voulue
interface--> filmService : ajouter_a_watchlist()
filmService->dao: **Ajout** de la watchlist à la BDD
dao->db: **Stockage** de la nouvelle watchlist dans la BDD


@enduml
