@startuml 

skinparam backgroundColor #F5F5F5
skinparam activity {
    BackgroundColor #d3f4ff
    BorderColor #030108
    ArrowColor #030108
    FontName Arial
    FontSize 14
    FontColor #030108
}
skinparam decision {
    BackgroundColor #030108
    BorderColor #030108
}
skinparam start {
    BackgroundColor #32CD32
    BorderColor #008000
}
skinparam end {
    BackgroundColor #ff6347
    BorderColor #030108
}

start

:Utilisateur crée ou se connecte;

:Utilisateur ajoute films à la watchlist;

:Système analyse la watchlist;

if (Critères de recommandation ?) then (Meilleur ratio prix/nombre de films)
    :Rechercher abonnements;
else (Plus de films dans la watchlist)
    :Rechercher abonnements;
endif

:Comparer abonnements;
:Calculer le meilleur abonnement;
:Proposer le meilleur abonnement à l'utilisateur;

stop
@enduml
